### ISSUE TITLE
Reproducibility

### ISSUE THREAD

**Issue by aleflabo** [Owen-Tian/MAAM-NET#2]
Thank you for sharing the code publicly!

I want to reproduce the results you obtained in the paper, but I see no specifics about the environment used for the experiments. Can you share it, please?

In addition, the .flo files are requested as part of the dataset. Are they available?

Thanks in advance,
Alessandro Flaborea

**Comment by Owen-Tian** [comment]
1. The requirements file is attached to this project, we simply present all the package versions;
2. We haven't present the .flo files since the dataset mentioned in the paper is massive，we highly recommend extracting optical flow features through official code of Flownet2 rather than directly downloading them.
